exclude: "^$"
fail_fast: false
repos:
  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
        python_version: python3.6
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.3
    hooks:
      - id: python-bandit-vulnerability-check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.641
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.2.2
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
